// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GwDvJAoM39X74nAzgKkDnl-LJ0i69Io',
    appId: '1:819021649732:web:c03dc569cc2c21ae1aa911',
    messagingSenderId: '819021649732',
    projectId: 'king-service-dfa96',
    authDomain: 'king-service-dfa96.firebaseapp.com',
    storageBucket: 'king-service-dfa96.firebasestorage.app',
    measurementId: 'G-JH9F6QDCPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3-GdnY8GNqmmd1DGvBAAJ3EaslwCe9g',
    appId: '1:819021649732:android:71e61ac5b37080041aa911',
    messagingSenderId: '819021649732',
    projectId: 'king-service-dfa96',
    storageBucket: 'king-service-dfa96.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GwDvJAoM39X74nAzgKkDnl-LJ0i69Io',
    appId: '1:819021649732:web:fa48ca471e1339761aa911',
    messagingSenderId: '819021649732',
    projectId: 'king-service-dfa96',
    authDomain: 'king-service-dfa96.firebaseapp.com',
    storageBucket: 'king-service-dfa96.firebasestorage.app',
    measurementId: 'G-6PJNCCTT4N',
  );
}
